fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.0
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=775"]
    - id: check-merge-conflict
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.5.0
  hooks:
    - id: reorder-python-imports
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args: ["--config=setup.cfg"]
